openapi: 3.0.1
info:
  title: Family Asset Management
  description: Helps to keep a record of bought products and goods
  version: 1.0.0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /home/products:
    get:
      tags:
      - asset-controller
      operationId: getAllProducts
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      tags:
      - asset-controller
      operationId: addProduct
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Product'
components:
  schemas:
    Product:
      type: object